monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: php://stderr
                level: info
                channels: [ "!event", "!doctrine", "!console" ]
                formatter: monolog.formatter.line
            full:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 2
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine" ]
            deprecation:
                type: rotating_file
                channels: [ deprecation ]
                path: "%kernel.logs_dir%/deprecation.log"
                formatter: monolog.formatter.json
                max_files: 2

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                channels: [ "!event" ]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            deprecation:
                type: rotating_file
                channels: [ deprecation ]
                path: "%kernel.logs_dir%/deprecation.log"
                formatter: monolog.formatter.json
                max_files: 2

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
                channels: [ "!event", "!deprecation" ]
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine" ]
                formatter: monolog.formatter.json
            deprecation:
                type: rotating_file
                channels: [ deprecation ]
                path: "%kernel.logs_dir%/deprecation.log"
                formatter: monolog.formatter.json
                max_files: 2
